// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIYTR-X9Z3lOAGyAcZ73O278Y2L8YKL6s',
    appId: '1:747433836587:web:37ae79639d830ccbb72a6e',
    messagingSenderId: '747433836587',
    projectId: 'in-class-mad',
    authDomain: 'in-class-mad.firebaseapp.com',
    storageBucket: 'in-class-mad.appspot.com',
    measurementId: 'G-WP7G9YQ948',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ayFskwo4qeXYCecDwZyh0v_nrZEUjdk',
    appId: '1:747433836587:android:d91ec7cbeac238a6b72a6e',
    messagingSenderId: '747433836587',
    projectId: 'in-class-mad',
    storageBucket: 'in-class-mad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG_1fUnFhgkZwoJ83Ba67xStHbbeo_RI4',
    appId: '1:747433836587:ios:1e698746b8ed9032b72a6e',
    messagingSenderId: '747433836587',
    projectId: 'in-class-mad',
    storageBucket: 'in-class-mad.appspot.com',
    iosBundleId: 'com.example.madFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG_1fUnFhgkZwoJ83Ba67xStHbbeo_RI4',
    appId: '1:747433836587:ios:1e698746b8ed9032b72a6e',
    messagingSenderId: '747433836587',
    projectId: 'in-class-mad',
    storageBucket: 'in-class-mad.appspot.com',
    iosBundleId: 'com.example.madFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIYTR-X9Z3lOAGyAcZ73O278Y2L8YKL6s',
    appId: '1:747433836587:web:c965429456642d9bb72a6e',
    messagingSenderId: '747433836587',
    projectId: 'in-class-mad',
    authDomain: 'in-class-mad.firebaseapp.com',
    storageBucket: 'in-class-mad.appspot.com',
    measurementId: 'G-2ZMDXZ60XR',
  );
}
